export interface Carta {
	idCarta: number,
	nombre: string,
	idSet: number,
	descripcionSet: string,
	stock: number,
	precio: number,
	esActivo: boolean,
	coste: string,
	tipo: string,
	rareza: string,
	texto: string,
	artista: string,
	numero: string,
	poder: string,
	resistencia: string,
	imagenUrl: string,
}
